feat: introduced cleanup for the gateway tables
dailydotdev/daily-gateway pull request #384
Opened 2021-11-19 10:12 UTC by rebelchris

DD-59

**Related PRs:**
[API](https://github.com/dailydotdev/daily-api/pull/800) and [Apps](https://github.com/dailydotdev/apps/pull/701)

**Description:**
This introduces the cleanup for the gateway tables.
Note that a CDC already exists for the deletion of a user, so I'm leveraging that to cleanup the API.

No new test where introduced

2021-11-21 16:17 UTC, idoshamun requested changes
I love to see you are active on the backend as well :)

2021-11-21 16:17 UTC, idoshamun commented on src/routes/users.js
> +  }
This should be done in the background using a worker.
Why? Most of the time when we have to deal with two uncoordinated systems (MySQL and Sendgrid, in this case) we would like to set one of them as the source of truth and the second as a replicate or secondary. Otherwise what happens when one succeeds and the other fails? Should the endpoint fail or succeed?
So it's safer to delete from MySQL in the endpoint and in the worker remove the user from the mailing list.

2021-11-21 16:17 UTC, idoshamun commented on src/routes/users.js
> +router.post('/delete', async (ctx) => {
I suggest changing the method to `delete` and the endpoint to `/me`. I also raised it in the Apps

2021-11-21 16:17 UTC, idoshamun commented on src/routes/users.js
> +    logout(ctx);
Instead of creating an anonymous function, you can pass `logout` directly

2021-11-22 08:33 UTC, rebelchris commented on src/routes/users.js
> +  }
Thanks for explaining, makes total sense and altered it

2021-11-22 08:40 UTC, rebelchris commented
@idoshamun Changed the mailing deletion to a worker, could you verify this is the way to do it?

2021-11-22 10:03 UTC, idoshamun requested changes
Great work on the worker

2021-11-22 10:03 UTC, idoshamun commented on src/routes/users.js
> +  await userModel.deleteAccount(userId);
This should happen in a single transaction

2021-11-22 12:00 UTC, rebelchris commented
@idoshamun Would you mind checking if I did this transaction alright?
For reference I used it as described here:
https://stackoverflow.com/questions/59502244/multiple-operations-in-knex-transaction?rq=1

2021-11-22 12:57 UTC, idoshamun approved these changes
Looks great now!

2021-11-22 13:32 UTC, merged