refactor: boot user's settings
dailydotdev/daily-gateway pull request #394
Opened 2021-12-16 10:32 UTC by sshanzel

DD-337

The subscription end for utilizing the boot query with the user's settings.

The default values were fetched from the info in our APIs entity.

2021-12-16 12:08 UTC, idoshamun requested changes
This looks neat. I love the fact that it becomes easier to embed more properties to the boot query with time.
I think we can remove the legacy properties from the defaults object because a client which relies on the boot query no longer expect to use these.
I do think that we should try structure this process. The alerts and settings flow look pretty much the same. You can create a function that receives some other functions as helpers. But the general workflow is the same so I recommend structuring it into a function.

2021-12-16 12:35 UTC, rebelchris requested changes
Wow this is looking pretty slick man!
Really nice we can quickly serve this to prevent further delay on the basic settings.

2021-12-16 12:35 UTC, rebelchris commented on src/redis.js
> +  openSidebar: true,
Do note this is now: `sidebarExpanded`

2021-12-16 12:35 UTC, rebelchris commented on src/redis.js
> +      showTopSites
I think `sidebarExpanded` is already available to be fetched here.

2021-12-16 13:29 UTC, sshanzel commented on src/redis.js
> +  openSidebar: true,
Ah, we were just literally discussing this earlier 😆  thank you for the mention! 🚢

2021-12-17 11:54 UTC, sshanzel commented
Once the [relevant API ](https://github.com/dailydotdev/daily-api/pull/834)for this integration has been merged, we can then safely review this PR.

2021-12-20 07:49 UTC, sshanzel commented
This should now be ready for review since the relevant API has been merged 🚢

2021-12-20 11:26 UTC, idoshamun approved these changes
Wow! This PR is so great.
I love how you abstracted away the workflow of using the cache and introducing something new to the boot query

2021-12-21 00:05 UTC, sshanzel commented
@idoshamun thank you for the awesome review!

@rebelchris kindly let me know if you require further changes. Thank you! 🚢

2021-12-21 02:52 UTC, rebelchris approved these changes
Wow really nice work here @sshanzel 
Super cool what you've done with this.

Just one small non-blocking comment.

2021-12-21 02:52 UTC, rebelchris commented on src/redis.js
>        // TODO: use a dedicated logger for exceptions
Should we do anything with this at this point?
Maybe even a console.error so they at least show up?

2021-12-21 03:13 UTC, sshanzel commented on src/redis.js
>        // TODO: use a dedicated logger for exceptions
Very good point! Let's use a console.error for this to make debugging much easier.

2021-12-21 03:18 UTC, merged

2021-12-21 03:18 UTC, sshanzel commented
Thank you both! 🚢