feat: companion
dailydotdev/daily-gateway pull request #429
Opened 2022-03-07 11:29 UTC by rebelchris

Introducing the new boot endpoint for the companion.
This is a post request that passes the URL which we can match based on canonicalUrls.

It will in turn query the API GraphQL layer, and also retrieve the users settings from the API.

dd-458

2022-03-07 12:18 UTC, rebelchris commented
I'm super interested what you guys think of the test case.
It almost felt a bit "artificial" as we basically mock and expect the mock, but it seems to be how the other test for the gateway run as well.

2022-03-08 07:03 UTC, idoshamun requested changes
We need some changes here before we proceed.
Haven't looked at the tests yet because we need to change the route.

2022-03-08 07:26 UTC, rebelchris commented on src/redis.js
> +export const POST_DEFAULT = {
I'm using this for a test, as the default object.

2022-03-08 07:26 UTC, rebelchris commented on src/routes/boot.js
> +router.post(
Because we are posting the canonical url to it.
Would you rather have we send it as a get param?

2022-03-08 09:36 UTC, rebelchris commented on src/integration.js
> +export const getFromDailyGraphQLApi = (ctx, query) => getFromDailyApi(ctx, 'POST', '/graphql', query);
It's actually not used by anything else anymore.

2022-03-08 11:45 UTC, rebelchris commented
Thanks for that @idoshamun 
Refactored to get, and added the visit and boot logic.

Also modified to reflect the changes on the API.

2022-03-08 12:44 UTC, idoshamun approved these changes
A small change and we're ready to go

2022-03-08 12:44 UTC, idoshamun commented on src/routes/boot.js
> +  '/companion/:url',
I thought we will use a query param. Not sure if this will work. Because the URL parameter contains some characters that we have to escape

2022-03-08 12:44 UTC, idoshamun commented on src/integration.js
> +export const getFromDailyGraphQLApi = (ctx, query) => getFromDailyApi(ctx, 'POST', '/graphql', query);
We can delete it then

2022-03-08 12:52 UTC, rebelchris commented on src/routes/boot.js
> +  '/companion/:url',
Can switch it to query param, I think either way we have to escape it since we pass a URL (urlencode)

2022-03-08 12:58 UTC, idoshamun commented on src/routes/boot.js
> +  '/companion/:url',
I agree but it's safer as a query param I think. My intuition basically can't put words but I'm not feeling safe to pass it as part of the path.

2022-03-08 13:11 UTC, merged