feat: introducing boot changes to support Kratos flow
dailydotdev/daily-gateway pull request #503
Opened 2022-08-04 11:50 UTC by rebelchris

Added optional flow to support the Kratos users.
Tried to use as much as the original flow as we could.

Once we reach 90% user base we can modify the flow and remove all legacy code.

Things to note:
- Does Kratos whoami refresh the token?
- We should introduce roles in the Kratos traits if possible (it's only moderator rights)

WT-296

2022-08-04 11:51 UTC, rebelchris commented on src/cookies.js
> +  return '127.0.0.1';
We should fix this 😅

2022-08-07 10:19 UTC, idoshamun requested changes
Very well thought PR!
I love the backward compatibility mindset you demonstrated here. 🤩

2022-08-07 10:19 UTC, idoshamun commented on .env
> +KRATOS_ORIGIN='http://127.0.0.1:4433'
Do you think we need to replace all `localhost` with `127.0.0.1` to make it consistent?

2022-08-07 10:19 UTC, idoshamun commented on src/auth.js
> +      ctx.state.user = { userId: kratos?.identity?.id };
```suggestion
      ctx.state.user = { userId: kratos.identity.id, isKratos: true };
```

2022-08-07 10:19 UTC, idoshamun commented on src/auth.js
> +    ctx.state.isKratos = true;
I suggest moving it into `validateKratosToken`. (suggestion provided already above)

2022-08-08 09:47 UTC, rebelchris commented on .env
> +KRATOS_ORIGIN='http://127.0.0.1:4433'
Probably nicer, no urgent need though.
I'll do it for the sake of uniforming it 🙏

2022-08-08 10:07 UTC, idoshamun approved these changes

2022-08-08 13:06 UTC, merged